### ISSUE TITLE
chaosmonkey migrate not working

### ISSUE THREAD

**Issue by tingzhang1210** [Netflix/chaosmonkey#12]
ERROR - couldn't apply database migration: database migration failed: Error 1067: Invalid default value for 'killed_at' handling 1.0.0_initial_schema.sqlroot

**Comment by lorin** [comment]
@tingzhang1210 Which version of mysql are you using?

**Comment by tingzhang1210** [comment]
5.5

**Comment by tingzhang1210** [comment]
# mysql -V
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by lorin** [comment]
It appears that the migration works with 5.6, but not 5.5.53.

I can reproduce the problem on 5.5.53:

```
$ chaosmonkey migrate
ERROR - couldn't apply database migration: database migration failed: Error 1067: Invalid default value for 'killed_at' handling 1.0.0_initial_schema.sql%
```

And I can verify that it works find on 5.6:

```
$ chaosmonkey migrate
[ 7850] 2016/11/01 20:25:13 Successfully applied database migrations. Number of migrations applied:  1
database migration applied successfully
```

Are you able to upgrade versions?

**Comment by tingzhang1210** [comment]
yeah, update to 5.6, it works for me, thanks!
