### ISSUE TITLE
Build instructions are incomplete

### ISSUE THREAD

**Issue by caipre** [Netflix/chaosmonkey#18]
I wasn't able to build the package using the instructions [from the wiki.](https://github.com/Netflix/chaosmonkey/wiki/How-to-deploy#build)

```
$ cat /etc/issue
Ubuntu 14.04 LTS
$ export GOPATH=$HOME/gocode
$ go version
go version go1.6 linux/amd64
$ go get github.com/Netflix/chaosmonkey/bin/chaosmonkey
package github.com/Netflix/chaosmonkey/bin/chaosmonkey: cannot find package "github.com/Netflix/chaosmonkey/bin/chaosmonkey" in any of:
        /usr/lib/go/src/github.com/Netflix/chaosmonkey/bin/chaosmonkey (from $GOROOT)
        /home/user/gocode/src/github.com/Netflix/chaosmonkey/bin/chaosmonkey (from $GOPATH)
```

A friend suggested `go get github.com/Netflix/chaosmonkey...` , which seems to have worked. Perhaps the build instructions should be changed? My experience with `go` is limited, so maybe this is common knowledge among gophers. I also noticed that the minimum supported `go` version is not documented anywhere, if it matters for the build.

**Comment by lorin** [comment]
There was a recent change to the code that wasn't reflected in a change to the wiki. Try this instead:

```
go get github.com/Netflix/chaosmonkey/cmd/chaosmonkey
```
