### ISSUE TITLE
chaosmonkey supports only instance termination?

### ISSUE THREAD

**Issue by kkhamruddin-pk** [Netflix/chaosmonkey#46]
Chaos monkey latest version supports only instance termination?

How do I need to check failures at all levels like CPU, Memory, Harddisk, Network, Load etc.

How do I can install chaos monkey older version that supports all of the above features? Is there any documentation?

**Comment by lorin** [comment]
The previous version lives in a project called [SimianArmy](https://github.com/netflix/simianarmy). The [wiki](https://github.com/netflix/simianarmy/wiki) for that project contains the documentation.

Simian Army is no longer actively supported, but there is a community of people that still use it, so you could ask questions on the [Simian Army Google Group](https://groups.google.com/forum/#!forum/simianarmy-users), but you might not get a response.

**Comment by lorin** [comment]
I should note that we don't have plans to support other types of failure injection with the current Chaos Monkey. For a list of other open source chaos tools, check out https://github.com/dastergon/awesome-chaos-engineering#notable-tools

**Comment by kkhamruddin-pk** [comment]
Thank you lorin, will go through it.
