### ISSUE TITLE
chaosmonkey eligible gives "json unmarshal failed: unexpected end of JSON input"

### ISSUE THREAD

**Issue by sb185234** [Netflix/chaosmonkey#50]
Dear Team,

I am trying to use Chaosmonkey for our resiliency testing in GKE (Google Kuberenetes Engine),
I have deployed spinnaker and followed the instructions from here (https://blog.spinnaker.io/running-chaos-monkey-on-spinnaker-google-compute-engine-gce-155dc52f20ef). 
Now after having everything set, the command chaosmonkey config <appname> gives me the below output:

(*chaosmonkey.AppConfig)(0xc4200529c0)({
 Enabled: (bool) true,
 RegionsAreIndependent: (bool) true,
 MeanTimeBetweenKillsInWorkDays: (int) 2,
 MinTimeBetweenKillsInWorkDays: (int) 1,
 Grouping: (chaosmonkey.Group) cluster,
 Exceptions: ([]chaosmonkey.Exception) {
 },
 Whitelist: (*[]chaosmonkey.Exception)(<nil>)
})

But when trying to check for the eligible server groups it gives below error:
spinnaker@hal-123:~$ chaosmonkey eligible sireeapp1 spinnaker-service-account
**retrieve cloud provider failed: json unmarshal failed: unexpected end of JSON input**

Can you please let me know in which json file the error is being thrown and what should be the fix for it.

Thank you
Sireesha

**Comment by sb185234** [comment]
Never  mind after giving the correct account name it is working fine. But I think it should throw proper error when wrong account name is given along with the application name

Thank you
Sireesha

**Comment by lorin** [comment]
I agree, current the error message is not helpful to a user trying to troubleshoot the problem. I'm going to close this issue, but I opened up #52.
