### ISSUE TITLE
chaosmonkey terminate appname account gives "No eligible instances in group, nothing to terminate" even though I have instances in the group.

### ISSUE THREAD

**Issue by sb185234** [Netflix/chaosmonkey#51]
Dear Team,
I am trying to use Chaosmonkey for our resiliency testing in GKE (Google Kuberenetes Engine),
when giving the below for terminating the instance it gives below error even though I have instances for the application. Can you please guide me fix this issue.

 spinnaker@hal-123:~$ chaosmonkey terminate sireeapp1 spinnaker-service-account
**[ 5083] 2019/01/11 11:53:01 WARNING: eligible.Instances failed for InstanceGroup{app=sireeapp1 account=spinnaker-service-account region= stack= cluster=}: retrieve cloud provider failed: json unmarshal failed: unexpected end of JSON input
[ 5083] 2019/01/11 11:53:01 No eligible instances in group, nothing to terminate: InstanceGroup{app=sireeapp1 account=spinnaker-service-account region= stack= cluster=}**

Note:  I can see two instances for the application as below in spinnaker UI.
![image](https://user-images.githubusercontent.com/45787721/51032838-73fac400-15c7-11e9-830b-2c210af76363.png)

Thank you
Sireesha

**Comment by sb185234** [comment]
Never mind after giving the correct account name it is working fine. But I think it should throw proper error when wrong account name is given along with the application name

Thank you
Sireesha

**Comment by banghuaji** [comment]
> Never mind after giving the correct account name it is working fine. But I think it should throw proper error when wrong account name is given along with the application name
> 
> Thank you
> Sireesha

Ihave the same error,where can we find the  correct account .

spnnaker version : 1.8.0
kubernetes version ：v1.10.2

```
[root@localhost ~]# chaosmonkey terminate chaosnginx my-k8s-v2-account 
[ 7152] 2019/04/19 11:24:32 No eligible instances in group, nothing to terminate: InstanceGroup{app=chaosnginx account=my-k8s-v2-account region= stack= cluster=}
```
with spinnaker ui ,we can find the pod.
![image](https://user-images.githubusercontent.com/17561338/56405917-303be880-62a1-11e9-9a3c-cd19c11c3124.png)

**Comment by sb185234** [comment]
In my case "my-k8s-v2-account" is the account name, you can find from the
UI. in the left side tab *Account* section. (there is one more account
"protest")

Thanks
Sireesha
