### ISSUE TITLE
Error message is not meaningful when wrong account name used

### ISSUE THREAD

**Issue by lorin** [Netflix/chaosmonkey#52]
If the user specifies the wrong account name, then the `chaosmonkey eligible` command yields the following error:

```
spinnaker@hal-123:~$ chaosmonkey eligible sireeapp1 spinnaker-service-account
retrieve cloud provider failed: json unmarshal failed: unexpected end of JSON input
```

This error message doesn't provide the user with information about what the problem and how to fix it. Chaos Monkey should provide a more meaningful error message in this scenario.

See #50 and #51.

**Comment by prytoegrian** [comment]
Hi !
I'd like to take my chance on this ticket. Do I have to know something specific about it ?

**Comment by lorin** [comment]
@prytoegrian Great! Check out #50 and #51 for more details on the current behavior. I don't think there's anything else specific you need to know.

**Comment by Zyqsempai** [comment]
@prytoegrian Are you still working on it? If not, i will be gald to take this one!

**Comment by prytoegrian** [comment]
Yep. I was very busy lasts weeks but I know exactly how to correct this flaw. I'll propose my PR soon.
