### ISSUE TITLE
Use database migration to automate database setup

### ISSUE THREAD

**Issue by syamantm** [Netflix/chaosmonkey#9]
First step in automating the installation/setup process would be to automate the database setup.
Using a db migration tool would be ideal in this case.

The proposal is instead of applying the [database change manually](https://github.com/Netflix/chaosmonkey/wiki/How-to-deploy#set-up-the-mysql-database), we just have to do the following at boot/init.d or at any convenient time to apply the database changes:

```
chaosmonkey migrate
```

Is this something you would be interested in ?

**Comment by lorin** [comment]
Yep, I think this is a good idea.

**Comment by syamantm** [comment]
Thanks, opened https://github.com/Netflix/chaosmonkey/pull/10
